#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-sysklogd
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_sysklogd.tar.gz

echo "+=================+"
echo "| sysklogd-1.3-31 |"
echo "+=================+"
cd $TMP
tar xzvf $CWD/sysklogd-1.3-31.tar.gz
cd sysklogd-1.3-31
make
make syslog_tst
cat klogd > $PKG/usr/sbin/klogd
cat syslog_tst > $PKG/usr/sbin/syslog_tst
cat syslogd > $PKG/usr/sbin/syslogd
for page in klogd.8 sysklogd.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done
cat syslog.conf.5 | gzip -9c > $PKG/usr/man/man5/syslog.conf.5.gz
cp -a ANNOUNCE COPYING INSTALL MANIFEST NEWS README.1st \
  README.linux Sysklogd-1.3.lsm $PKG/usr/doc/sysklogd
chown root.root $PKG/usr/doc/sysklogd/*
chmod 644 $PKG/usr/doc/sysklogd/*

# Build the package:
cd $PKG
tar czvf $TMP/sysklogd.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/sysklogd-1.3-31
  rm -rf $PKG
fi
