#!/bin/sh
# This script is invoked when installing manual entries.  It generates
# additional links to manual entries, corresponding to the procedure
# and command names described by the manual entry.  For example, the
# Tcl manual entry Hash.3.gz describes procedures Tcl_InitHashTable,
# Tcl_CreateHashEntry, and many more.  This script will make hard
# links so that Tcl_InitHashTable.3.gz, Tcl_CreateHashEntry.3.gz, and so
# on all refer to Hash.3.gz in the installed directory.
#
# Because of the length of command and procedure names, this mechanism
# only works on machines that support file names longer than 14 characters.
# This script checks to see if long file names are supported, and it
# doesn't make any links if they are not.
#
# The script takes one argument, which is the name of the directory
# where the manual entries have been installed.

if test $# != 1; then
    echo "Usage: mkLinks dir"
    exit 1
fi

cd $1
echo foo > xyzzyTestingAVeryLongFileName.foo
x=`echo xyzzyTe*`
rm xyzzyTe*
if test "$x" != "xyzzyTestingAVeryLongFileName.foo"; then
    exit
fi
if test -r safe.n.gz; then
    rm -f Base.n.gz
    ln -s safe.n.gz Base.n.gz
fi
if test -r http.n.gz; then
    rm -f Http.n.gz
    ln -s http.n.gz Http.n.gz
fi
if test -r safe.n.gz; then
    rm -f Safe.n.gz
    ln -s safe.n.gz Safe.n.gz
fi
if test -r StringObj.3.gz; then
    rm -f TclConcatObj.3.gz
    ln -s StringObj.3.gz TclConcatObj.3.gz
fi
if test -r AddErrInfo.3.gz; then
    rm -f Tcl_AddErrorInfo.3.gz
    ln -s AddErrInfo.3.gz Tcl_AddErrorInfo.3.gz
fi
if test -r AddErrInfo.3.gz; then
    rm -f Tcl_AddObjErrorInfo.3.gz
    ln -s AddErrInfo.3.gz Tcl_AddObjErrorInfo.3.gz
fi
if test -r Alloc.3.gz; then
    rm -f Tcl_Alloc.3.gz
    ln -s Alloc.3.gz Tcl_Alloc.3.gz
fi
if test -r AllowExc.3.gz; then
    rm -f Tcl_AllowExceptions.3.gz
    ln -s AllowExc.3.gz Tcl_AllowExceptions.3.gz
fi
if test -r AppInit.3.gz; then
    rm -f Tcl_AppInit.3.gz
    ln -s AppInit.3.gz Tcl_AppInit.3.gz
fi
if test -r ObjectType.3.gz; then
    rm -f Tcl_AppendAllObjTypes.3.gz
    ln -s ObjectType.3.gz Tcl_AppendAllObjTypes.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_AppendElement.3.gz
    ln -s SetResult.3.gz Tcl_AppendElement.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_AppendResult.3.gz
    ln -s SetResult.3.gz Tcl_AppendResult.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_AppendStringsToObj.3.gz
    ln -s StringObj.3.gz Tcl_AppendStringsToObj.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_AppendToObj.3.gz
    ln -s StringObj.3.gz Tcl_AppendToObj.3.gz
fi
if test -r Async.3.gz; then
    rm -f Tcl_AsyncCreate.3.gz
    ln -s Async.3.gz Tcl_AsyncCreate.3.gz
fi
if test -r Async.3.gz; then
    rm -f Tcl_AsyncDelete.3.gz
    ln -s Async.3.gz Tcl_AsyncDelete.3.gz
fi
if test -r Async.3.gz; then
    rm -f Tcl_AsyncInvoke.3.gz
    ln -s Async.3.gz Tcl_AsyncInvoke.3.gz
fi
if test -r Async.3.gz; then
    rm -f Tcl_AsyncMark.3.gz
    ln -s Async.3.gz Tcl_AsyncMark.3.gz
fi
if test -r BackgdErr.3.gz; then
    rm -f Tcl_BackgroundError.3.gz
    ln -s BackgdErr.3.gz Tcl_BackgroundError.3.gz
fi
if test -r Backslash.3.gz; then
    rm -f Tcl_Backslash.3.gz
    ln -s Backslash.3.gz Tcl_Backslash.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_BadChannelOption.3.gz
    ln -s CrtChannel.3.gz Tcl_BadChannelOption.3.gz
fi
if test -r CallDel.3.gz; then
    rm -f Tcl_CallWhenDeleted.3.gz
    ln -s CallDel.3.gz Tcl_CallWhenDeleted.3.gz
fi
if test -r DoWhenIdle.3.gz; then
    rm -f Tcl_CancelIdleCall.3.gz
    ln -s DoWhenIdle.3.gz Tcl_CancelIdleCall.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Close.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Close.3.gz
fi
if test -r CmdCmplt.3.gz; then
    rm -f Tcl_CommandComplete.3.gz
    ln -s CmdCmplt.3.gz Tcl_CommandComplete.3.gz
fi
if test -r Concat.3.gz; then
    rm -f Tcl_Concat.3.gz
    ln -s Concat.3.gz Tcl_Concat.3.gz
fi
if test -r SplitList.3.gz; then
    rm -f Tcl_ConvertElement.3.gz
    ln -s SplitList.3.gz Tcl_ConvertElement.3.gz
fi
if test -r ObjectType.3.gz; then
    rm -f Tcl_ConvertToType.3.gz
    ln -s ObjectType.3.gz Tcl_ConvertToType.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_CreateAlias.3.gz
    ln -s CrtSlave.3.gz Tcl_CreateAlias.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_CreateAliasObj.3.gz
    ln -s CrtSlave.3.gz Tcl_CreateAliasObj.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_CreateChannel.3.gz
    ln -s CrtChannel.3.gz Tcl_CreateChannel.3.gz
fi
if test -r CrtChnlHdlr.3.gz; then
    rm -f Tcl_CreateChannelHandler.3.gz
    ln -s CrtChnlHdlr.3.gz Tcl_CreateChannelHandler.3.gz
fi
if test -r CrtCloseHdlr.3.gz; then
    rm -f Tcl_CreateCloseHandler.3.gz
    ln -s CrtCloseHdlr.3.gz Tcl_CreateCloseHandler.3.gz
fi
if test -r CrtCommand.3.gz; then
    rm -f Tcl_CreateCommand.3.gz
    ln -s CrtCommand.3.gz Tcl_CreateCommand.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_CreateEventSource.3.gz
    ln -s Notifier.3.gz Tcl_CreateEventSource.3.gz
fi
if test -r Exit.3.gz; then
    rm -f Tcl_CreateExitHandler.3.gz
    ln -s Exit.3.gz Tcl_CreateExitHandler.3.gz
fi
if test -r CrtFileHdlr.3.gz; then
    rm -f Tcl_CreateFileHandler.3.gz
    ln -s CrtFileHdlr.3.gz Tcl_CreateFileHandler.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_CreateHashEntry.3.gz
    ln -s Hash.3.gz Tcl_CreateHashEntry.3.gz
fi
if test -r CrtInterp.3.gz; then
    rm -f Tcl_CreateInterp.3.gz
    ln -s CrtInterp.3.gz Tcl_CreateInterp.3.gz
fi
if test -r CrtMathFnc.3.gz; then
    rm -f Tcl_CreateMathFunc.3.gz
    ln -s CrtMathFnc.3.gz Tcl_CreateMathFunc.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_CreateObjCommand.3.gz
    ln -s CrtObjCmd.3.gz Tcl_CreateObjCommand.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_CreateSlave.3.gz
    ln -s CrtSlave.3.gz Tcl_CreateSlave.3.gz
fi
if test -r CrtTimerHdlr.3.gz; then
    rm -f Tcl_CreateTimerHandler.3.gz
    ln -s CrtTimerHdlr.3.gz Tcl_CreateTimerHandler.3.gz
fi
if test -r CrtTrace.3.gz; then
    rm -f Tcl_CreateTrace.3.gz
    ln -s CrtTrace.3.gz Tcl_CreateTrace.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringAppend.3.gz
    ln -s DString.3.gz Tcl_DStringAppend.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringAppendElement.3.gz
    ln -s DString.3.gz Tcl_DStringAppendElement.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringEndSublist.3.gz
    ln -s DString.3.gz Tcl_DStringEndSublist.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringFree.3.gz
    ln -s DString.3.gz Tcl_DStringFree.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringGetResult.3.gz
    ln -s DString.3.gz Tcl_DStringGetResult.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringInit.3.gz
    ln -s DString.3.gz Tcl_DStringInit.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringLength.3.gz
    ln -s DString.3.gz Tcl_DStringLength.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringResult.3.gz
    ln -s DString.3.gz Tcl_DStringResult.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringSetLength.3.gz
    ln -s DString.3.gz Tcl_DStringSetLength.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringStartSublist.3.gz
    ln -s DString.3.gz Tcl_DStringStartSublist.3.gz
fi
if test -r DString.3.gz; then
    rm -f Tcl_DStringValue.3.gz
    ln -s DString.3.gz Tcl_DStringValue.3.gz
fi
if test -r Object.3.gz; then
    rm -f Tcl_DecrRefCount.3.gz
    ln -s Object.3.gz Tcl_DecrRefCount.3.gz
fi
if test -r AssocData.3.gz; then
    rm -f Tcl_DeleteAssocData.3.gz
    ln -s AssocData.3.gz Tcl_DeleteAssocData.3.gz
fi
if test -r CrtChnlHdlr.3.gz; then
    rm -f Tcl_DeleteChannelHandler.3.gz
    ln -s CrtChnlHdlr.3.gz Tcl_DeleteChannelHandler.3.gz
fi
if test -r CrtCloseHdlr.3.gz; then
    rm -f Tcl_DeleteCloseHandler.3.gz
    ln -s CrtCloseHdlr.3.gz Tcl_DeleteCloseHandler.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_DeleteCommand.3.gz
    ln -s CrtObjCmd.3.gz Tcl_DeleteCommand.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_DeleteCommandFromToken.3.gz
    ln -s CrtObjCmd.3.gz Tcl_DeleteCommandFromToken.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_DeleteEventSource.3.gz
    ln -s Notifier.3.gz Tcl_DeleteEventSource.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_DeleteEvents.3.gz
    ln -s Notifier.3.gz Tcl_DeleteEvents.3.gz
fi
if test -r Exit.3.gz; then
    rm -f Tcl_DeleteExitHandler.3.gz
    ln -s Exit.3.gz Tcl_DeleteExitHandler.3.gz
fi
if test -r CrtFileHdlr.3.gz; then
    rm -f Tcl_DeleteFileHandler.3.gz
    ln -s CrtFileHdlr.3.gz Tcl_DeleteFileHandler.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_DeleteHashEntry.3.gz
    ln -s Hash.3.gz Tcl_DeleteHashEntry.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_DeleteHashTable.3.gz
    ln -s Hash.3.gz Tcl_DeleteHashTable.3.gz
fi
if test -r CrtInterp.3.gz; then
    rm -f Tcl_DeleteInterp.3.gz
    ln -s CrtInterp.3.gz Tcl_DeleteInterp.3.gz
fi
if test -r CrtTimerHdlr.3.gz; then
    rm -f Tcl_DeleteTimerHandler.3.gz
    ln -s CrtTimerHdlr.3.gz Tcl_DeleteTimerHandler.3.gz
fi
if test -r CrtTrace.3.gz; then
    rm -f Tcl_DeleteTrace.3.gz
    ln -s CrtTrace.3.gz Tcl_DeleteTrace.3.gz
fi
if test -r DetachPids.3.gz; then
    rm -f Tcl_DetachPids.3.gz
    ln -s DetachPids.3.gz Tcl_DetachPids.3.gz
fi
if test -r DoOneEvent.3.gz; then
    rm -f Tcl_DoOneEvent.3.gz
    ln -s DoOneEvent.3.gz Tcl_DoOneEvent.3.gz
fi
if test -r DoWhenIdle.3.gz; then
    rm -f Tcl_DoWhenIdle.3.gz
    ln -s DoWhenIdle.3.gz Tcl_DoWhenIdle.3.gz
fi
if test -r CallDel.3.gz; then
    rm -f Tcl_DontCallWhenDeleted.3.gz
    ln -s CallDel.3.gz Tcl_DontCallWhenDeleted.3.gz
fi
if test -r Object.3.gz; then
    rm -f Tcl_DuplicateObj.3.gz
    ln -s Object.3.gz Tcl_DuplicateObj.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Eof.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Eof.3.gz
fi
if test -r Eval.3.gz; then
    rm -f Tcl_Eval.3.gz
    ln -s Eval.3.gz Tcl_Eval.3.gz
fi
if test -r Eval.3.gz; then
    rm -f Tcl_EvalFile.3.gz
    ln -s Eval.3.gz Tcl_EvalFile.3.gz
fi
if test -r EvalObj.3.gz; then
    rm -f Tcl_EvalObj.3.gz
    ln -s EvalObj.3.gz Tcl_EvalObj.3.gz
fi
if test -r Preserve.3.gz; then
    rm -f Tcl_EventuallyFree.3.gz
    ln -s Preserve.3.gz Tcl_EventuallyFree.3.gz
fi
if test -r Exit.3.gz; then
    rm -f Tcl_Exit.3.gz
    ln -s Exit.3.gz Tcl_Exit.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_ExposeCommand.3.gz
    ln -s CrtSlave.3.gz Tcl_ExposeCommand.3.gz
fi
if test -r ExprLong.3.gz; then
    rm -f Tcl_ExprBoolean.3.gz
    ln -s ExprLong.3.gz Tcl_ExprBoolean.3.gz
fi
if test -r ExprLongObj.3.gz; then
    rm -f Tcl_ExprBooleanObj.3.gz
    ln -s ExprLongObj.3.gz Tcl_ExprBooleanObj.3.gz
fi
if test -r ExprLong.3.gz; then
    rm -f Tcl_ExprDouble.3.gz
    ln -s ExprLong.3.gz Tcl_ExprDouble.3.gz
fi
if test -r ExprLongObj.3.gz; then
    rm -f Tcl_ExprDoubleObj.3.gz
    ln -s ExprLongObj.3.gz Tcl_ExprDoubleObj.3.gz
fi
if test -r ExprLong.3.gz; then
    rm -f Tcl_ExprLong.3.gz
    ln -s ExprLong.3.gz Tcl_ExprLong.3.gz
fi
if test -r ExprLongObj.3.gz; then
    rm -f Tcl_ExprLongObj.3.gz
    ln -s ExprLongObj.3.gz Tcl_ExprLongObj.3.gz
fi
if test -r ExprLongObj.3.gz; then
    rm -f Tcl_ExprObj.3.gz
    ln -s ExprLongObj.3.gz Tcl_ExprObj.3.gz
fi
if test -r ExprLong.3.gz; then
    rm -f Tcl_ExprString.3.gz
    ln -s ExprLong.3.gz Tcl_ExprString.3.gz
fi
if test -r Exit.3.gz; then
    rm -f Tcl_Finalize.3.gz
    ln -s Exit.3.gz Tcl_Finalize.3.gz
fi
if test -r FindExec.3.gz; then
    rm -f Tcl_FindExecutable.3.gz
    ln -s FindExec.3.gz Tcl_FindExecutable.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_FindHashEntry.3.gz
    ln -s Hash.3.gz Tcl_FindHashEntry.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_FirstHashEntry.3.gz
    ln -s Hash.3.gz Tcl_FirstHashEntry.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Flush.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Flush.3.gz
fi
if test -r Alloc.3.gz; then
    rm -f Tcl_Free.3.gz
    ln -s Alloc.3.gz Tcl_Free.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_GetAlias.3.gz
    ln -s CrtSlave.3.gz Tcl_GetAlias.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_GetAliasObj.3.gz
    ln -s CrtSlave.3.gz Tcl_GetAliasObj.3.gz
fi
if test -r AssocData.3.gz; then
    rm -f Tcl_GetAssocData.3.gz
    ln -s AssocData.3.gz Tcl_GetAssocData.3.gz
fi
if test -r GetInt.3.gz; then
    rm -f Tcl_GetBoolean.3.gz
    ln -s GetInt.3.gz Tcl_GetBoolean.3.gz
fi
if test -r BoolObj.3.gz; then
    rm -f Tcl_GetBooleanFromObj.3.gz
    ln -s BoolObj.3.gz Tcl_GetBooleanFromObj.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_GetChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_GetChannel.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelBufferSize.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelBufferSize.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelHandle.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelHandle.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelInstanceData.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelInstanceData.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelMode.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelMode.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelName.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelName.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_GetChannelOption.3.gz
    ln -s OpenFileChnl.3.gz Tcl_GetChannelOption.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_GetChannelType.3.gz
    ln -s CrtChannel.3.gz Tcl_GetChannelType.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_GetCommandInfo.3.gz
    ln -s CrtObjCmd.3.gz Tcl_GetCommandInfo.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_GetCommandName.3.gz
    ln -s CrtObjCmd.3.gz Tcl_GetCommandName.3.gz
fi
if test -r GetInt.3.gz; then
    rm -f Tcl_GetDouble.3.gz
    ln -s GetInt.3.gz Tcl_GetDouble.3.gz
fi
if test -r DoubleObj.3.gz; then
    rm -f Tcl_GetDoubleFromObj.3.gz
    ln -s DoubleObj.3.gz Tcl_GetDoubleFromObj.3.gz
fi
if test -r SetErrno.3.gz; then
    rm -f Tcl_GetErrno.3.gz
    ln -s SetErrno.3.gz Tcl_GetErrno.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_GetHashKey.3.gz
    ln -s Hash.3.gz Tcl_GetHashKey.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_GetHashValue.3.gz
    ln -s Hash.3.gz Tcl_GetHashValue.3.gz
fi
if test -r GetIndex.3.gz; then
    rm -f Tcl_GetIndexFromObj.3.gz
    ln -s GetIndex.3.gz Tcl_GetIndexFromObj.3.gz
fi
if test -r GetInt.3.gz; then
    rm -f Tcl_GetInt.3.gz
    ln -s GetInt.3.gz Tcl_GetInt.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_GetIntFromObj.3.gz
    ln -s IntObj.3.gz Tcl_GetIntFromObj.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_GetInterpPath.3.gz
    ln -s CrtSlave.3.gz Tcl_GetInterpPath.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_GetLongFromObj.3.gz
    ln -s IntObj.3.gz Tcl_GetLongFromObj.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_GetMaster.3.gz
    ln -s CrtSlave.3.gz Tcl_GetMaster.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_GetObjResult.3.gz
    ln -s SetResult.3.gz Tcl_GetObjResult.3.gz
fi
if test -r ObjectType.3.gz; then
    rm -f Tcl_GetObjType.3.gz
    ln -s ObjectType.3.gz Tcl_GetObjType.3.gz
fi
if test -r GetOpnFl.3.gz; then
    rm -f Tcl_GetOpenFile.3.gz
    ln -s GetOpnFl.3.gz Tcl_GetOpenFile.3.gz
fi
if test -r SplitPath.3.gz; then
    rm -f Tcl_GetPathType.3.gz
    ln -s SplitPath.3.gz Tcl_GetPathType.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_GetServiceMode.3.gz
    ln -s Notifier.3.gz Tcl_GetServiceMode.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_GetSlave.3.gz
    ln -s CrtSlave.3.gz Tcl_GetSlave.3.gz
fi
if test -r GetStdChan.3.gz; then
    rm -f Tcl_GetStdChannel.3.gz
    ln -s GetStdChan.3.gz Tcl_GetStdChannel.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_GetStringFromObj.3.gz
    ln -s StringObj.3.gz Tcl_GetStringFromObj.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_GetStringResult.3.gz
    ln -s SetResult.3.gz Tcl_GetStringResult.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_GetVar.3.gz
    ln -s SetVar.3.gz Tcl_GetVar.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_GetVar2.3.gz
    ln -s SetVar.3.gz Tcl_GetVar2.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Gets.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Gets.3.gz
fi
if test -r Eval.3.gz; then
    rm -f Tcl_GlobalEval.3.gz
    ln -s Eval.3.gz Tcl_GlobalEval.3.gz
fi
if test -r EvalObj.3.gz; then
    rm -f Tcl_GlobalEvalObj.3.gz
    ln -s EvalObj.3.gz Tcl_GlobalEvalObj.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_HashStats.3.gz
    ln -s Hash.3.gz Tcl_HashStats.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_HideCommand.3.gz
    ln -s CrtSlave.3.gz Tcl_HideCommand.3.gz
fi
if test -r Object.3.gz; then
    rm -f Tcl_IncrRefCount.3.gz
    ln -s Object.3.gz Tcl_IncrRefCount.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_InitHashTable.3.gz
    ln -s Hash.3.gz Tcl_InitHashTable.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_InputBlocked.3.gz
    ln -s OpenFileChnl.3.gz Tcl_InputBlocked.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_InputBuffered.3.gz
    ln -s OpenFileChnl.3.gz Tcl_InputBuffered.3.gz
fi
if test -r Interp.3.gz; then
    rm -f Tcl_Interp.3.gz
    ln -s Interp.3.gz Tcl_Interp.3.gz
fi
if test -r CrtInterp.3.gz; then
    rm -f Tcl_InterpDeleted.3.gz
    ln -s CrtInterp.3.gz Tcl_InterpDeleted.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_IsSafe.3.gz
    ln -s CrtSlave.3.gz Tcl_IsSafe.3.gz
fi
if test -r Object.3.gz; then
    rm -f Tcl_IsShared.3.gz
    ln -s Object.3.gz Tcl_IsShared.3.gz
fi
if test -r SplitPath.3.gz; then
    rm -f Tcl_JoinPath.3.gz
    ln -s SplitPath.3.gz Tcl_JoinPath.3.gz
fi
if test -r LinkVar.3.gz; then
    rm -f Tcl_LinkVar.3.gz
    ln -s LinkVar.3.gz Tcl_LinkVar.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjAppendElement.3.gz
    ln -s ListObj.3.gz Tcl_ListObjAppendElement.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjAppendList.3.gz
    ln -s ListObj.3.gz Tcl_ListObjAppendList.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjGetElements.3.gz
    ln -s ListObj.3.gz Tcl_ListObjGetElements.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjIndex.3.gz
    ln -s ListObj.3.gz Tcl_ListObjIndex.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjLength.3.gz
    ln -s ListObj.3.gz Tcl_ListObjLength.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_ListObjReplace.3.gz
    ln -s ListObj.3.gz Tcl_ListObjReplace.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_MakeFileChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_MakeFileChannel.3.gz
fi
if test -r CrtSlave.3.gz; then
    rm -f Tcl_MakeSafe.3.gz
    ln -s CrtSlave.3.gz Tcl_MakeSafe.3.gz
fi
if test -r OpenTcp.3.gz; then
    rm -f Tcl_MakeTcpClientChannel.3.gz
    ln -s OpenTcp.3.gz Tcl_MakeTcpClientChannel.3.gz
fi
if test -r SplitList.3.gz; then
    rm -f Tcl_Merge.3.gz
    ln -s SplitList.3.gz Tcl_Merge.3.gz
fi
if test -r BoolObj.3.gz; then
    rm -f Tcl_NewBooleanObj.3.gz
    ln -s BoolObj.3.gz Tcl_NewBooleanObj.3.gz
fi
if test -r DoubleObj.3.gz; then
    rm -f Tcl_NewDoubleObj.3.gz
    ln -s DoubleObj.3.gz Tcl_NewDoubleObj.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_NewIntObj.3.gz
    ln -s IntObj.3.gz Tcl_NewIntObj.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_NewListObj.3.gz
    ln -s ListObj.3.gz Tcl_NewListObj.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_NewLongObj.3.gz
    ln -s IntObj.3.gz Tcl_NewLongObj.3.gz
fi
if test -r Object.3.gz; then
    rm -f Tcl_NewObj.3.gz
    ln -s Object.3.gz Tcl_NewObj.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_NewStringObj.3.gz
    ln -s StringObj.3.gz Tcl_NewStringObj.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_NextHashEntry.3.gz
    ln -s Hash.3.gz Tcl_NextHashEntry.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_NotifyChannel.3.gz
    ln -s CrtChannel.3.gz Tcl_NotifyChannel.3.gz
fi
if test -r ObjSetVar.3.gz; then
    rm -f Tcl_ObjGetVar2.3.gz
    ln -s ObjSetVar.3.gz Tcl_ObjGetVar2.3.gz
fi
if test -r ObjSetVar.3.gz; then
    rm -f Tcl_ObjSetVar2.3.gz
    ln -s ObjSetVar.3.gz Tcl_ObjSetVar2.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_OpenCommandChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_OpenCommandChannel.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_OpenFileChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_OpenFileChannel.3.gz
fi
if test -r OpenTcp.3.gz; then
    rm -f Tcl_OpenTcpClient.3.gz
    ln -s OpenTcp.3.gz Tcl_OpenTcpClient.3.gz
fi
if test -r OpenTcp.3.gz; then
    rm -f Tcl_OpenTcpServer.3.gz
    ln -s OpenTcp.3.gz Tcl_OpenTcpServer.3.gz
fi
if test -r PkgRequire.3.gz; then
    rm -f Tcl_PkgProvide.3.gz
    ln -s PkgRequire.3.gz Tcl_PkgProvide.3.gz
fi
if test -r PkgRequire.3.gz; then
    rm -f Tcl_PkgRequire.3.gz
    ln -s PkgRequire.3.gz Tcl_PkgRequire.3.gz
fi
if test -r AddErrInfo.3.gz; then
    rm -f Tcl_PosixError.3.gz
    ln -s AddErrInfo.3.gz Tcl_PosixError.3.gz
fi
if test -r Preserve.3.gz; then
    rm -f Tcl_Preserve.3.gz
    ln -s Preserve.3.gz Tcl_Preserve.3.gz
fi
if test -r PrintDbl.3.gz; then
    rm -f Tcl_PrintDouble.3.gz
    ln -s PrintDbl.3.gz Tcl_PrintDouble.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_QueueEvent.3.gz
    ln -s Notifier.3.gz Tcl_QueueEvent.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Read.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Read.3.gz
fi
if test -r Alloc.3.gz; then
    rm -f Tcl_Realloc.3.gz
    ln -s Alloc.3.gz Tcl_Realloc.3.gz
fi
if test -r DetachPids.3.gz; then
    rm -f Tcl_ReapDetachedProcs.3.gz
    ln -s DetachPids.3.gz Tcl_ReapDetachedProcs.3.gz
fi
if test -r RecordEval.3.gz; then
    rm -f Tcl_RecordAndEval.3.gz
    ln -s RecordEval.3.gz Tcl_RecordAndEval.3.gz
fi
if test -r RecEvalObj.3.gz; then
    rm -f Tcl_RecordAndEvalObj.3.gz
    ln -s RecEvalObj.3.gz Tcl_RecordAndEvalObj.3.gz
fi
if test -r RegExp.3.gz; then
    rm -f Tcl_RegExpCompile.3.gz
    ln -s RegExp.3.gz Tcl_RegExpCompile.3.gz
fi
if test -r RegExp.3.gz; then
    rm -f Tcl_RegExpExec.3.gz
    ln -s RegExp.3.gz Tcl_RegExpExec.3.gz
fi
if test -r RegExp.3.gz; then
    rm -f Tcl_RegExpMatch.3.gz
    ln -s RegExp.3.gz Tcl_RegExpMatch.3.gz
fi
if test -r RegExp.3.gz; then
    rm -f Tcl_RegExpRange.3.gz
    ln -s RegExp.3.gz Tcl_RegExpRange.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_RegisterChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_RegisterChannel.3.gz
fi
if test -r ObjectType.3.gz; then
    rm -f Tcl_RegisterObjType.3.gz
    ln -s ObjectType.3.gz Tcl_RegisterObjType.3.gz
fi
if test -r Preserve.3.gz; then
    rm -f Tcl_Release.3.gz
    ln -s Preserve.3.gz Tcl_Release.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_ResetResult.3.gz
    ln -s SetResult.3.gz Tcl_ResetResult.3.gz
fi
if test -r SplitList.3.gz; then
    rm -f Tcl_ScanElement.3.gz
    ln -s SplitList.3.gz Tcl_ScanElement.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Seek.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Seek.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_ServiceAll.3.gz
    ln -s Notifier.3.gz Tcl_ServiceAll.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_ServiceEvent.3.gz
    ln -s Notifier.3.gz Tcl_ServiceEvent.3.gz
fi
if test -r AssocData.3.gz; then
    rm -f Tcl_SetAssocData.3.gz
    ln -s AssocData.3.gz Tcl_SetAssocData.3.gz
fi
if test -r BoolObj.3.gz; then
    rm -f Tcl_SetBooleanObj.3.gz
    ln -s BoolObj.3.gz Tcl_SetBooleanObj.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_SetChannelBufferSize.3.gz
    ln -s CrtChannel.3.gz Tcl_SetChannelBufferSize.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_SetChannelOption.3.gz
    ln -s OpenFileChnl.3.gz Tcl_SetChannelOption.3.gz
fi
if test -r CrtObjCmd.3.gz; then
    rm -f Tcl_SetCommandInfo.3.gz
    ln -s CrtObjCmd.3.gz Tcl_SetCommandInfo.3.gz
fi
if test -r CrtChannel.3.gz; then
    rm -f Tcl_SetDefaultTranslation.3.gz
    ln -s CrtChannel.3.gz Tcl_SetDefaultTranslation.3.gz
fi
if test -r DoubleObj.3.gz; then
    rm -f Tcl_SetDoubleObj.3.gz
    ln -s DoubleObj.3.gz Tcl_SetDoubleObj.3.gz
fi
if test -r SetErrno.3.gz; then
    rm -f Tcl_SetErrno.3.gz
    ln -s SetErrno.3.gz Tcl_SetErrno.3.gz
fi
if test -r AddErrInfo.3.gz; then
    rm -f Tcl_SetErrorCode.3.gz
    ln -s AddErrInfo.3.gz Tcl_SetErrorCode.3.gz
fi
if test -r Hash.3.gz; then
    rm -f Tcl_SetHashValue.3.gz
    ln -s Hash.3.gz Tcl_SetHashValue.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_SetIntObj.3.gz
    ln -s IntObj.3.gz Tcl_SetIntObj.3.gz
fi
if test -r ListObj.3.gz; then
    rm -f Tcl_SetListObj.3.gz
    ln -s ListObj.3.gz Tcl_SetListObj.3.gz
fi
if test -r IntObj.3.gz; then
    rm -f Tcl_SetLongObj.3.gz
    ln -s IntObj.3.gz Tcl_SetLongObj.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_SetMaxBlockTime.3.gz
    ln -s Notifier.3.gz Tcl_SetMaxBlockTime.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_SetObjLength.3.gz
    ln -s StringObj.3.gz Tcl_SetObjLength.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_SetObjResult.3.gz
    ln -s SetResult.3.gz Tcl_SetObjResult.3.gz
fi
if test -r SetRecLmt.3.gz; then
    rm -f Tcl_SetRecursionLimit.3.gz
    ln -s SetRecLmt.3.gz Tcl_SetRecursionLimit.3.gz
fi
if test -r SetResult.3.gz; then
    rm -f Tcl_SetResult.3.gz
    ln -s SetResult.3.gz Tcl_SetResult.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_SetServiceMode.3.gz
    ln -s Notifier.3.gz Tcl_SetServiceMode.3.gz
fi
if test -r GetStdChan.3.gz; then
    rm -f Tcl_SetStdChannel.3.gz
    ln -s GetStdChan.3.gz Tcl_SetStdChannel.3.gz
fi
if test -r StringObj.3.gz; then
    rm -f Tcl_SetStringObj.3.gz
    ln -s StringObj.3.gz Tcl_SetStringObj.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_SetTimer.3.gz
    ln -s Notifier.3.gz Tcl_SetTimer.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_SetVar.3.gz
    ln -s SetVar.3.gz Tcl_SetVar.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_SetVar2.3.gz
    ln -s SetVar.3.gz Tcl_SetVar2.3.gz
fi
if test -r Sleep.3.gz; then
    rm -f Tcl_Sleep.3.gz
    ln -s Sleep.3.gz Tcl_Sleep.3.gz
fi
if test -r SplitList.3.gz; then
    rm -f Tcl_SplitList.3.gz
    ln -s SplitList.3.gz Tcl_SplitList.3.gz
fi
if test -r SplitPath.3.gz; then
    rm -f Tcl_SplitPath.3.gz
    ln -s SplitPath.3.gz Tcl_SplitPath.3.gz
fi
if test -r StaticPkg.3.gz; then
    rm -f Tcl_StaticPackage.3.gz
    ln -s StaticPkg.3.gz Tcl_StaticPackage.3.gz
fi
if test -r StrMatch.3.gz; then
    rm -f Tcl_StringMatch.3.gz
    ln -s StrMatch.3.gz Tcl_StringMatch.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Tell.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Tell.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_TraceVar.3.gz
    ln -s TraceVar.3.gz Tcl_TraceVar.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_TraceVar2.3.gz
    ln -s TraceVar.3.gz Tcl_TraceVar2.3.gz
fi
if test -r Translate.3.gz; then
    rm -f Tcl_TranslateFileName.3.gz
    ln -s Translate.3.gz Tcl_TranslateFileName.3.gz
fi
if test -r LinkVar.3.gz; then
    rm -f Tcl_UnlinkVar.3.gz
    ln -s LinkVar.3.gz Tcl_UnlinkVar.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_UnregisterChannel.3.gz
    ln -s OpenFileChnl.3.gz Tcl_UnregisterChannel.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_UnsetVar.3.gz
    ln -s SetVar.3.gz Tcl_UnsetVar.3.gz
fi
if test -r SetVar.3.gz; then
    rm -f Tcl_UnsetVar2.3.gz
    ln -s SetVar.3.gz Tcl_UnsetVar2.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_UntraceVar.3.gz
    ln -s TraceVar.3.gz Tcl_UntraceVar.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_UntraceVar2.3.gz
    ln -s TraceVar.3.gz Tcl_UntraceVar2.3.gz
fi
if test -r UpVar.3.gz; then
    rm -f Tcl_UpVar.3.gz
    ln -s UpVar.3.gz Tcl_UpVar.3.gz
fi
if test -r UpVar.3.gz; then
    rm -f Tcl_UpVar2.3.gz
    ln -s UpVar.3.gz Tcl_UpVar2.3.gz
fi
if test -r LinkVar.3.gz; then
    rm -f Tcl_UpdateLinkedVar.3.gz
    ln -s LinkVar.3.gz Tcl_UpdateLinkedVar.3.gz
fi
if test -r Eval.3.gz; then
    rm -f Tcl_VarEval.3.gz
    ln -s Eval.3.gz Tcl_VarEval.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_VarTraceInfo.3.gz
    ln -s TraceVar.3.gz Tcl_VarTraceInfo.3.gz
fi
if test -r TraceVar.3.gz; then
    rm -f Tcl_VarTraceInfo2.3.gz
    ln -s TraceVar.3.gz Tcl_VarTraceInfo2.3.gz
fi
if test -r Notifier.3.gz; then
    rm -f Tcl_WaitForEvent.3.gz
    ln -s Notifier.3.gz Tcl_WaitForEvent.3.gz
fi
if test -r OpenFileChnl.3.gz; then
    rm -f Tcl_Write.3.gz
    ln -s OpenFileChnl.3.gz Tcl_Write.3.gz
fi
if test -r WrongNumArgs.3.gz; then
    rm -f Tcl_WrongNumArgs.3.gz
    ln -s WrongNumArgs.3.gz Tcl_WrongNumArgs.3.gz
fi
if test -r pkgMkIndex.n.gz; then
    rm -f pkg_mkIndex.n.gz
    ln -s pkgMkIndex.n.gz pkg_mkIndex.n.gz
fi
exit 0
