#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES XV (xview3.2p1-X11R6)" \
       --checklist "Please select the packages you wish to install \
from series XV. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Press ENTER when you are \
done." 19 70 8 \
"xvol32" "Binaries for xview3.2p1-X11R6" "on" \
"xv32_so" "Shared libraries for xview3.2p1-X11R6" "on" \
"xv32_a" "Static libraries for xview3.2p1-X11R6" "off" \
"xv32exmp" "Sample programs for Xview" "off" \
"xvinc32" "Include files for Xview programming" "on" \
"xvmenus" "Menus for the OpenLook Window Manager" "on" \
"sspkg" "SlingShot extensions and examples for XView" "off" \
"workman" "An audio CD player for XView" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in xv32_so xvol32 workman xv32_a xv32exmp xvinc32 xvmenus sspkg ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in xv32_a xv32exmp xvinc32 xvmenus xvol32 xv32_so \
sspkg workman ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
