#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-joe
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_joe.tar.gz

# Function to handle manpage source:
man2gz () { # $1 is source page name, $2 is target name for preformatted
            # output (full path && name) and $3 is the same, but for the
            # source.
  mkdir -p `dirname $2`
  groff -s -p -t -e -Tascii -mandoc $1 | gzip -9c > $2
  if [ ! "$3" = "" ]; then
    mkdir -p `dirname $3`
    cat $1 > $3 
  fi 
}

echo "+========+"
echo "| joe2.8 |"
echo "+========+"
cd $TMP
tar xzvf $CWD/joe2.8.tar.gz
cd joe
zcat $CWD/joe2.8.diff.gz | patch
mkdir -p $PKG/usr/doc/joe2.8
cp -a INFO TODO LIST README VERSION $PKG/usr/doc/joe2.8
chmod 644 $PKG/usr/doc/joe2.8/*
chown root.root $PKG/usr/doc/joe2.8/*
cat joerc > $PKG/usr/lib/joe/joerc
cat jstarrc > $PKG/usr/lib/joe/jstarrc
cat jmacsrc > $PKG/usr/lib/joe/jmacsrc
cat jpicorc > $PKG/usr/lib/joe/jpicorc
cat rjoerc > $PKG/usr/lib/joe/rjoerc
make
make termidx
strip joe termidx
cat joe > $PKG/usr/bin/joe
cat termidx > $PKG/usr/bin/termidx
cat joe.1 | gzip -9c > $PKG/usr/man/man1/joe.1.gz

# Build the package:
cd $PKG
tar czvf $TMP/joe.tgz .

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/joe
  rm -rf $PKG
fi
