#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-sc
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_sc.tar.gz

echo "+=========+"
echo "| sc-6.21 |"
echo "+=========+"
cd $TMP
tar xzvf $CWD/sc621.linux.tar.gz
cd sc621
zcat $CWD/sc621.linux.diff.gz | patch
make
strip sc
cat sc > $PKG/usr/bin/sc
cat scqref > $PKG/usr/bin/scqref
cat psc > $PKG/usr/bin/psc
cat sc.doc | gzip -9c > $PKG/usr/man/man1/sc.1.gz

# Build the package:
cd $PKG
tar czvf $TMP/sc.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/sc621
  rm -rf $PKG
fi
