tar xzvf apache_1.3.6.tar.gz
cd apache_1.3.6
./configure --prefix=/var/lib/apache \
            --bindir=/var/lib/apache/bin \
            --sbindir=/var/lib/apache/sbin \
            --runtimedir=/var/run \
            --logfiledir=/var/log \
            --enable-module=so \
            --enable-shared=max
make
