#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-procps

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_procps.tar.gz

echo "+==============+"
echo "| procps-2.0.2 |"
echo "+==============+"
cd $TMP
tar xzvf $CWD/procps-2.0.2.tar.gz
cd procps-2.0.2
mkdir -p $PKG/usr/doc/procps-2.0.2
cp -a BUGS COPYING COPYING.LIB INSTALL NEWS TODO $PKG/usr/doc/procps-2.0.2
chown root.root $PKG/usr/doc/procps-2.0.2/*
chmod 644 $PKG/usr/doc/procps-2.0.2/*
# Fix a couple annoying things:
zcat $CWD/procps.top-nobright.diff.gz | patch
zcat $CWD/procps.nowarning.diff.gz | patch
make
cat kill > $PKG/bin/kill
cat ps/ps> $PKG/bin/ps
cat proc/libproc.so.2.0.0 > $PKG/lib/libproc.so.2.0.0
cat XConsole > $PKG/usr/X11R6/bin/XConsole
cat free > $PKG/bin/free
cat oldps > $PKG/usr/bin/oldps
cat skill > $PKG/usr/bin/skill
# links to 'kill'
# cat snice > $PKG/usr/bin/snice
# $PKG/usr/bin/snice -> skill
cat tload > $PKG/usr/bin/tload
cat top > $PKG/usr/bin/top
cat uptime > $PKG/usr/bin/uptime
cat vmstat > $PKG/usr/bin/vmstat
cat w > $PKG/usr/bin/w
cat watch > $PKG/usr/bin/watch
cp ps/ps.1 .
for page in free.1 kill.1 oldps.1 ps.1 skill.1 snice.1 tload.1 \
  top.1 uptime.1 w.1 watch.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
for page in vmstat.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done

echo "+===========+"
echo "| psmisc-18 |"
echo "+===========+"
cd $TMP
tar xzvf $CWD/psmisc-18.tar.gz
cd psmisc
mkdir -p $PKG/usr/doc/psmisc
cp -a VERSION README INSTALL CHANGES COPYING $PKG/usr/doc/psmisc
chmod 644 $PKG/usr/doc/psmisc/*
chown root.root $PKG/usr/doc/psmisc/*
make
strip fuser pstree killall
cat fuser > $PKG/usr/bin/fuser
cat pstree > $PKG/usr/bin/pstree
cat killall > $PKG/bin/killall
for page in fuser.1 killall.1 pstree.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done

echo "+=============+"
echo "| procinfo-16 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/procinfo-16.tar.gz
cd procinfo-16
mkdir -p $PKG/usr/doc/procinfo-16
cp -a CHANGES README TODO $PKG/usr/doc/procinfo-16
chmod 644 $PKG/usr/doc/procinfo-16/*
chown root.root $PKG/usr/doc/procinfo-16/*
make
strip procinfo
cat procinfo > $PKG/usr/bin/procinfo
cat lsdev.pl > $PKG/usr/bin/lsdev
cat socklist.pl > $PKG/usr/bin/socklist
for page in procinfo.8 lsdev.8 socklist.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done

# Build the package:
cd $PKG
tar czvf $TMP/procps.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/procps-2.0.2
  rm -rf $TMP/procinfo-16
  rm -rf $TMP/psmisc
  rm -rf $PKG
fi
