#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-tcpip1
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_tcpip1.tar.gz
# This is for the "blue underscore" effect, already patched in.
#( cd $PKG ; zcat $CWD/termcap.diff.gz | patch )
#( cd $PKG ; rm etc/termcap.orig )

# Find the size of a file:
filesize() {
 SIZE=`ls -l -d -G $1 | cut -b23-32`
 echo -n $SIZE
}

echo "+======================+"
echo "| nfs-server-2.2beta40 |"
echo "+======================+"
cd $TMP
tar xzvf $CWD/nfs-server-2.2beta40.tar.gz
cd nfs-server-2.2beta40
mkdir -p $PKG/usr/doc/nfs-server-2.2beta40
cp -a README NEWS $PKG/usr/doc/nfs-server-2.2beta40
chmod 644 $PKG/usr/doc/nfs-server-2.2beta40/*
chown root.root $PKG/usr/doc/nfs-server-2.2beta40/*
./BUILD
make
strip rpc.mountd rpc.nfsd showmount
cat rpc.mountd > $PKG/usr/sbin/rpc.mountd
cat rpc.nfsd > $PKG/usr/sbin/rpc.nfsd
cat showmount > $PKG/usr/sbin/showmount
cat exports.man | gzip -9c > $PKG/usr/man/man5/exports.5.gz
for page in mountd.man nfsd.man showmount.man ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/`basename $page .man`.8.gz
done

echo "+==================+"
echo "| tcp_wrappers_7.6 |"
echo "+==================+"
cd $TMP
tar xzvf $CWD/tcp_wrappers_7.6.tar.gz
cd tcp_wrappers_7.6
zcat $CWD/tcp_wrappers_7.6.diff.gz | patch
make REAL_DAEMON_DIR=/usr/sbin linux
strip tcpd
cat tcpd > $PKG/usr/sbin/tcpd
cat libwrap.a > $PKG/usr/lib/libwrap.a
cat tcpd.h > $PKG/usr/include/tcpd.h
make clean
make REAL_DAEMON_DIR=/usr/sbin/real-daemon-dir linux
strip tcpd safe_finger tcpdchk tcpdmatch try-from
cat tcpd > $PKG/usr/sbin/real-daemon-dir/tcpd
cat safe_finger > $PKG/usr/sbin/real-daemon-dir/safe_finger
cat tcpdchk > $PKG/usr/sbin/real-daemon-dir/tcpdchk
cat tcpdmatch > $PKG/usr/sbin/real-daemon-dir/tcpdmatch
cat try-from > $PKG/usr/sbin/real-daemon-dir/try-from
cat hosts_access.3 | gzip -9c > $PKG/usr/man/man3/hosts_access.3.gz
cat hosts_access.5 | gzip -9c > $PKG/usr/man/man5/hosts_access.5.gz
cat hosts_options.5 | gzip -9c > $PKG/usr/man/man5/hosts_options.5.gz
cat tcpd.8 | gzip -9c > $PKG/usr/man/man8/tcpd.8.gz
cat tcpdchk.8 | gzip -9c > $PKG/usr/man/man8/tcpdchk.8.gz
cat tcpdmatch.8 | gzip -9c > $PKG/usr/man/man8/tcpdmatch.8.gz

echo "+===============+"
echo "| icmpinfo-1.10 |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/icmpinfo-1.10.tar.gz
cd icmpinfo-1.10
zcat $CWD/icmpinfo-1.10.diff.gz | patch
make
strip icmpinfo
cat icmpinfo > $PKG/usr/sbin/icmpinfo
gzip -9c icmpinfo.man > $PKG/usr/man/man1/icmpinfo.1.gz

echo "+===============+"
echo "| pidentd-2.8.3 |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/pidentd-2.8.3.tar.gz
cd pidentd-2.8.3
zcat $CWD/pidentd-2.8.3.diff.gz | patch
mkdir -p $PKG/usr/doc/pidentd-2.8.3
cp -a CREDITS ChangeLog FAQ INSTALL README TODO $PKG/usr/doc/pidentd-2.8.3
cp -a doc $PKG/usr/doc/pidentd-2.8.3
( cd $PKG/usr/doc/pidentd-2.8.3 ; chown -R root.root * )
make linux
strip in.identd idecrypt itest
cat in.identd > $PKG/usr/sbin/in.identd
cat identd.man | gzip -9c > $PKG/usr/man/man8/identd.8.gz
echo ".so man8/identd.8" | gzip -9c > $PKG/usr/man/man8/in.identd.8.gz
cat idecrypt > $PKG/usr/sbin/idecrypt
chown root.bin $PKG/usr/sbin/idecrypt
chmod 755 $PKG/usr/sbin/idecrypt
cat idecrypt.man | gzip -9c > $PKG/usr/man/man8/idecrypt.8.gz
cat itest > $PKG/usr/doc/pidentd-2.8.3/itest
chmod 755 $PKG/usr/doc/pidentd-2.8.3/itest

echo "+===================+"
echo "| traceroute-4.4BSD |"
echo "+===================+"
cd $TMP
tar xzvf $CWD/traceroute-4.4BSD.tar.gz
cd traceroute-4.4BSD
zcat $CWD/traceroute-4.4BSD.diff.gz | patch
make
strip traceroute
cat traceroute > $PKG/usr/bin/traceroute
gzip -9c traceroute.8 > $PKG/usr/man/man8/traceroute.8.gz

echo "+================+"
echo "| net-tools-1.52 |"
echo "+================+"
cd $TMP
tar xzvf $CWD/net-tools-1.52.tar.gz
cd net-tools-1.52
zcat $CWD/net-tools-1.52.diff.gz | patch -p1
mkdir -p $PKG/usr/doc/net-tools-1.52
cp -a README $PKG/usr/doc/net-tools-1.52
chmod 644 $PKG/usr/doc/net-tools-1.52/*
chown root.root $PKG/usr/doc/net-tools-1.52/*
make
strip hostname arp ifconfig rarp route netstat plipconfig
cat arp > $PKG/sbin/arp
cat ifconfig > $PKG/sbin/ifconfig
cat rarp > $PKG/sbin/rarp
cat route > $PKG/sbin/route
cat hostname > $PKG/bin/hostname
cat netstat > $PKG/bin/netstat
cat plipconfig > $PKG/sbin/plipconfig
cd man/en_US
for page in dnsdomainname.1 domainname.1 hostname.1 nisdomainname.1 \
  ypdomainname.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
for page in arp.8 ifconfig.8 netstat.8 rarp.8 route.8 plipconfig.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done

echo "+=============+"
echo "| ruptime-570 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/ruptime-570.tar.gz
cd ruptime
make
strip ruptime
cat ruptime > $PKG/usr/bin/ruptime
cat ruptime.1 | gzip -9c > $PKG/usr/man/man1/ruptime.1.gz

echo "+=========+"
echo "| netdate |"
echo "+=========+"
cd $TMP
tar xzvf $CWD/netdate.tar.gz
cd netdate
zcat $CWD/netdate.diff.gz | patch
make
strip netdate
cat netdate > $PKG/usr/sbin/netdate
cat netdate.8 | gzip -9c > $PKG/usr/man/man8/netdate.8.gz

echo "+==================+"
echo "| netkit-base-0.10 |"
echo "+==================+"
cd $TMP
tar xzvf $CWD/netkit-base-0.10.tar.gz
cd netkit-base-0.10
./configure --prefix=/usr
make
cd inetd
strip inetd
cat inetd > $PKG/usr/sbin/inetd
cat inetd.8 | gzip -9c > $PKG/usr/man/man8/inetd.8.gz
cd ../ping
strip ping
cat ping > $PKG/bin/ping
cat ping.8 | gzip -9c > $PKG/usr/man/man8/ping.8.gz
cd ../rpcgen
strip rpcgen
cat rpcgen > $PKG/usr/bin/rpcgen
cat rpcgen.1 | gzip -9c > $PKG/usr/man/man1/rpcgen.1.gz
cd ../rpcinfo
strip rpcinfo
cat rpcinfo > $PKG/usr/sbin/rpcinfo
cat rpcinfo.8 | gzip -9c > $PKG/usr/man/man8/rpcinfo.8.gz

echo "+==================+"
echo "| biff+comsat-0.10 |"
echo "+==================+"
cd $TMP
tar xzvf $CWD/biff+comsat-0.10.tar.gz
cd biff+comsat-0.10
./configure --prefix=/usr
make
cd biff
strip biff
cat biff > $PKG/usr/bin/biff
cat biff.1 | gzip -9c > $PKG/usr/man/man1/biff.1.gz
cd ../comsat
strip comsat
cat comsat > $PKG/usr/sbin/in.comsat
cat comsat.8 | gzip -9c > $PKG/usr/man/man8/in.comsat.8.gz

echo "+=================+"
echo "| bsd-finger-0.10 |"
echo "+=================+"
cd $TMP
tar xzvf $CWD/bsd-finger-0.10.tar.gz
cd bsd-finger-0.10
./configure --prefix=/usr
make
cd finger
strip finger
cat finger > $PKG/usr/bin/finger
cat finger.1 | gzip -9c > $PKG/usr/man/man1/finger.1.gz
cd ../fingerd
strip fingerd
cat fingerd > $PKG/usr/sbin/in.fingerd
cat fingerd.8 | gzip -9c > $PKG/usr/man/man8/in.fingerd.8.gz

echo "+========================+"
echo "| netkit-bootparamd-0.10 |"
echo "+========================+"
cd $TMP
tar xzvf $CWD/netkit-bootparamd-0.10.tar.gz
cd netkit-bootparamd-0.10
./configure --prefix=/usr
make
cd rpc.bootparamd
cat bootparamd > $PKG/usr/sbin/rpc.bootparamd
cat callbootd > $PKG/usr/bin/callbootd
gzip -9c bootparamd.8 > $PKG/usr/man/man8/rpc.bootparamd.8.gz

echo "+=================+"
echo "| netkit-ftp-0.10 |"
echo "+=================+"
cd $TMP
tar xzvf $CWD/netkit-ftp-0.10.tar.gz
cd netkit-ftp-0.10
./configure --prefix=/usr
make
cd ftp
strip ftp
cat ftp > $PKG/bin/ftp
cat ftp.1 | gzip -9c > $PKG/usr/man/man1/ftp.1.gz

echo "+===================+"
echo "| netkit-ntalk-0.10 |"
echo "+===================+"
cd $TMP
tar xzvf $CWD/netkit-ntalk-0.10.tar.gz
cd netkit-ntalk-0.10
zcat $CWD/netkit-ntalk-0.10.diff.gz | patch
./configure --prefix=/usr
make
cd talk
strip talk
cat talk > $PKG/usr/bin/talk
cat talk.1 | gzip -9c > $PKG/usr/man/man1/talk.1.gz
cd ../talkd
strip talkd
cat talkd > $PKG/usr/sbin/in.talkd
cat talkd.8 | gzip -9c > $PKG/usr/man/man8/in.talkd.8.gz

echo "+====================+"
echo "| netkit-routed-0.12 |"
echo "+====================+"
cd $TMP
tar xzvf $CWD/netkit-routed-0.12.tar.gz
cd netkit-routed-0.12
./configure --prefix=/usr
make
strip routed/routed routed-query/routed-query routed-trace/routed-trace
cat routed/routed > $PKG/usr/sbin/routed
cat routed/routed.8.gz > $PKG/usr/man/man8/routed.8.gz
cat routed-query/routed-query > $PKG/usr/sbin/routed-query
cat routed-query/routed-query.8.gz > $PKG/usr/man/man8/routed-query.8.gz
cat routed-trace/routed-trace > $PKG/usr/sbin/routed-trace
cat routed-trace/routed-trace.8.gz > $PKG/usr/man/man8/routed-trace.8.gz

echo "+=================+"
echo "| netkit-rsh-0.10 |"
echo "+=================+"
cd $TMP
tar xzvf $CWD/netkit-rsh-0.10.tar.gz
cd netkit-rsh-0.10
zcat $CWD/netkit-rsh-0.10.diff.gz | patch
zcat $CWD/netkit-rsh-0.10.rexecd.diff.gz | patch
./configure --prefix=/usr
make
cd rsh
strip rsh
cat rsh > $PKG/usr/bin/rsh
cat rsh.1 | gzip -9c > $PKG/usr/man/man1/rsh.1.gz
cd ../rshd
strip rshd
cat rshd > $PKG/usr/sbin/in.rshd
cat rshd.8 | gzip -9c > $PKG/usr/man/man8/in.rshd.8.gz
cd ../rcp
cat rcp > $PKG/usr/bin/rcp
cat rcp.1 | gzip -9c > $PKG/usr/man/man1/rcp.1.gz
cd ../rexecd
strip rexecd
cat rexecd > $PKG/usr/sbin/in.rexecd
cat rexecd.8 | gzip -9c > $PKG/usr/man/man8/rexecd.8.gz
cd ../rlogin
strip rlogin
cat rlogin > $PKG/usr/bin/rlogin
cat rlogin.1 | gzip -9c > $PKG/usr/man/man1/rlogin.1.gz
cd ../rlogind
strip rlogind
cat rlogind > $PKG/usr/sbin/in.rlogind
cat rlogind.8 | gzip -9c > $PKG/usr/man/man8/in.rlogind.8.gz

echo "+====================+"
echo "| netkit-rusers-0.11 |"
echo "+====================+"
cd $TMP
tar xzvf $CWD/netkit-rusers-0.11.tar.gz
cd netkit-rusers-0.11
./configure --prefix=/usr
make
cd rpc.rusersd
strip rusersd
cat rusersd > $PKG/usr/sbin/rpc.rusersd
cat rpc.rusersd.8 | gzip -9c > $PKG/usr/man/man8/rpc.rusersd.8.gz
cd ../rusers
strip rusers
cat rusers > $PKG/usr/bin/rusers
cat rusers.1 | gzip -9c > $PKG/usr/man/man1/rusers.1.gz
cd ../rup
strip rup
cat rup > $PKG/usr/bin/rup
cat rup.1 | gzip -9c > $PKG/usr/man/man1/rup.1.gz

echo "+===================+"
echo "| netkit-rwall-0.10 |"
echo "+===================+"
cd $TMP
tar xzvf $CWD/netkit-rwall-0.10.tar.gz
cd netkit-rwall-0.10
./configure --prefix=/usr
make
cd rpc.rwalld
strip rwalld
cat rwalld > $PKG/usr/sbin/rpc.rwalld
cat rpc.rwalld.8 | gzip -9c > $PKG/usr/man/man8/rpc.rwalld.8.gz
cd ../rwall
strip rwall
cat rwall > $PKG/usr/bin/rwall
cat rwall.1 | gzip -9c > $PKG/usr/man/man1/rwall.1.gz

echo "+==================+"
echo "| netkit-rwho-0.10 |"
echo "+==================+"
cd $TMP
tar xzvf $CWD/netkit-rwho-0.10.tar.gz
cd netkit-rwho-0.10
./configure --prefix=/usr
make
cd rwho
strip rwho
cat rwho > $PKG/usr/bin/rwho
cat rwho.1 | gzip -9c > $PKG/usr/man/man1/rwho.1.gz
cd ../rwhod
strip rwhod
cat rwhod > $PKG/usr/sbin/rwhod
cat rwhod.8 | gzip -9c > $PKG/usr/man/man8/rwhod.8.gz

echo "+====================+"
echo "| netkit-telnet-0.12 |"
echo "+====================+"
cd $TMP
tar xzvf $CWD/netkit-telnet-0.12.tar.gz
cd netkit-telnet-0.12
./configure --prefix=/usr
make
cd telnet
strip telnet
cat telnet > $PKG/bin/telnet
cat telnet.1 | gzip -9c > $PKG/usr/man/man1/telnet.1.gz
cd ../telnetd
strip telnetd
cat telnetd > $PKG/usr/sbin/in.telnetd
cat telnetd.8 | gzip -9c > $PKG/usr/man/man8/in.telnetd.8.gz

echo "+==================+"
echo "| netkit-tftp-0.10 |"
echo "+==================+"
cd $TMP
tar xzvf $CWD/netkit-tftp-0.10.tar.gz
cd netkit-tftp-0.10
./configure --prefix=/usr
make
cd tftp
strip tftp
cat tftp > $PKG/usr/bin/tftp
cat tftp.1 | gzip -9c > $PKG/usr/man/man1/tftp.1.gz
cd ../tftpd
strip tftpd
cat tftpd > $PKG/usr/sbin/in.tftpd
cat tftpd.8 | gzip -9c > $PKG/usr/man/man8/in.tftpd.8.gz

echo "+===================+"
echo "| netkit-timed-0.10 |"
echo "+===================+"
cd $TMP
tar xzvf $CWD/netkit-timed-0.10.tar.gz
cd netkit-timed-0.10
./configure --prefix=/usr
make
cd timed/timed
strip timed
cat timed > $PKG/usr/sbin/in.timed
cat timed.8 | gzip -9c > $PKG/usr/man/man8/timed.8.gz
cd ../timedc
strip timedc
cat timedc > $PKG/usr/sbin/timedc
cat timedc.8 | gzip -9c > $PKG/usr/man/man8/timedc.8.gz

echo "+===============+"
echo "| netwrite-0.10 |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/netwrite-0.10.tar.gz
cd netwrite-0.10
./configure --prefix=/usr
make
cd write
cat write > $PKG/usr/bin/write
cat write.1 | gzip -9c > $PKG/usr/man/man1/write.1.gz
cat writed > $PKG/usr/sbin/in.writed
cat writed.8 | gzip -9c > $PKG/usr/man/man8/in.writed.8.gz

echo "+===============+"
echo "| portmap_5beta |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/portmap_5beta.tar.gz
cd portmap_5beta
zcat $CWD/portmap_5beta.diff.gz | patch
zcat $CWD/portmap_5beta.diff2.gz | patch
zcat $CWD/portmap_5beta.diff3.gz | patch
mkdir $PKG/usr/doc/portmap_5beta
cp -a BLURB CHANGES README $PKG/usr/doc/portmap_5beta
chmod 644 $PKG/usr/doc/portmap_5beta/*
chown root.root $PKG/usr/doc/portmap_5beta/*
make
strip portmap pmap_dump pmap_set
cat portmap > $PKG/sbin/rpc.portmap
cat pmap_dump > $PKG/usr/sbin/pmap_dump
cat pmap_set > $PKG/usr/sbin/pmap_set
cat portmap.8 | gzip -9c > $PKG/usr/man/man8/portmap.8.gz

echo "+=============+"
echo "| fwhois-1.00 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/fwhois-1.00.tar.gz
cd fwhois-1.00
make
cat fwhois > $PKG/usr/bin/fwhois

echo "+===============+"
echo "| wu-ftpd-2.6.0 |"
echo "+===============+"
cd $TMP
tar xzvf $CWD/wu-ftpd-2.6.0.tar.gz
cd wu-ftpd-2.6.0
zcat $CWD/wu-ftpd-2.6.0.diff.gz | patch -p1 -E
mkdir -p $PKG/usr/doc/wu-ftpd-2.6.0
cp -a CHANGES CONTRIBUTORS COPYRIGHT ERRATA INSTALL \
  LICENSE README README.AUTOCONF $PKG/usr/doc/wu-ftpd-2.6.0
cp -a doc/examples $PKG/usr/doc/wu-ftpd-2.6.0
chown root.root $PKG/usr/doc/wu-ftpd-2.6.0/* \
                $PKG/usr/doc/wu-ftpd-2.6.0/examples/*
./configure --prefix=/usr
make
cd bin
strip *
cat ckconfig > $PKG/usr/sbin/ckconfig
cat ftpcount > $PKG/usr/bin/ftpcount
cat ftpd > $PKG/usr/sbin/wu.ftpd
cat ftprestart > $PKG/usr/bin/ftprestart
cat ftpshut > $PKG/usr/bin/ftpshut
cat ftpwho > $PKG/usr/bin/ftpwho
cd ../doc
for page in ftpcount.1 ftpwho.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
for page in ftpaccess.5 xferlog.5 ftpconversions.5 ftphosts.5 ; do
  cat $page | gzip -9c > $PKG/usr/man/man5/$page.gz
done
for page in ftpd.8 ftpshut.8 ftprestart.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done
echo ".so man8/ftpd.8" | gzip -9c > $PKG/usr/man/man8/wu.ftpd.8.gz

echo "+=================+"
echo "| pcnfsd.93.02.16 |"
echo "+=================+"
cd $TMP
mkdir pcnfsd
cd pcnfsd
tar xzvf $CWD/pcnfsd.93.02.16.tar.gz
zcat $CWD/pcnfsd.93.02.16.diff.gz | patch
make clean
make bsd
mkdir -p $PKG/usr/doc/pcnfsd.93.02.16
cp -a README $PKG/usr/doc/pcnfsd.93.02.16
chown root.root $PKG/usr/doc/pcnfsd.93.02.16/README
cat pcnfsd.8c | gzip -9c > $PKG/usr/man/man8/pcnfsd.8.gz
cd bsd
strip clnt.pcnfsd rpc.pcnfsd
cat clnt.pcnfsd > $PKG/usr/sbin/clnt.pcnfsd
cat rpc.pcnfsd > $PKG/usr/sbin/rpc.pcnfsd

echo "+========+"
echo "| bwnfsd |"
echo "+========+"
cd $TMP
tar xzvf $CWD/bwnfsd.tar.gz
cd bwnfsd
zcat $CWD/bwnfsd.diff.gz | patch
make linux
strip bwnfsd
cat bwnfsd > $PKG/usr/sbin/rpc.bwnfsd

echo "+============+"
echo "| mini-inews |"
echo "+============+"
cd $TMP
tar xzvf $CWD/mini-inews.tar.gz
cd inews
make
strip inews
cat inews > $PKG/usr/bin/inews-nntp

echo "+==============+"
echo "| pop3d-1.006d |"
echo "+==============+"
cd $TMP
tar xzvf $CWD/pop3d-1.006d.tar.gz
cd pop3d-1.006d
zcat $CWD/pop3d-1.006d.diff.gz | patch
make
strip in.pop3d
cat in.pop3d > $PKG/usr/sbin/in.pop3d
gzip -9c pop3d.1 > $PKG/usr/man/man8/in.pop3d.8.gz
cp $CWD/flushpop.sh $PKG/usr/sbin/flushpop.sh
chown root.bin $PKG/usr/sbin/flushpop.sh
chmod 755 $PKG/usr/sbin/flushpop.sh

# Build the package:
cd $PKG
tar czvf $TMP/tcpip1.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
 for dir in biff+comsat-0.10 bsd-finger-0.10 bwnfsd fwhois-1.00 \
  icmpinfo-1.10 inews pcnfsd net-tools-1.50 netdate netkit-base-0.10 \
  netkit-bootparamd-0.10 netkit-ntalk-0.10 netkit-routed-0.12 \
  netkit-rsh-0.10 netkit-rusers-0.11 netkit-rwall-0.10 netkit-rwho-0.10 \
  netkit-telnet-0.10 netkit-tftp-0.10 netkit-timed-0.10 netwrite-0.10 \
  nfs-server-2.2beta40 package-tcpip1 pidentd-2.8.3 pop3d-1.006d \
  portmap_5beta ruptime tcp_wrappers_7.6 traceroute-4.4BSD \
  wu-ftpd-2.6.0 ; do
  rm -rf $TMP/$dir
 done
 rm -rf $PKG
fi
