#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-cpio
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_cpio.tar.gz

# Function to handle manpage source:
man2gz () { # $1 is source page name, $2 is target name for preformatted
            # output (full path && name) and $3 is the same, but for the
            # source.
  mkdir -p `dirname $2`
  groff -Tascii -mandoc $1 | gzip -9c > $2
  if [ ! "$3" = "" ]; then
    mkdir -p `dirname $3`
    cat $1 > $3 
  fi 
}

echo "+============+"
echo "| cpio-2.4.2 |"
echo "+============+"
cd $TMP
tar xzvf $CWD/cpio-2.4.2.tar.gz
cd cpio-2.4.2
configure --prefix=/usr
make CFLAGS=-O2 LDFLAGS=-s
cat cpio > $PKG/bin/cpio
cat mt > $PKG/bin/mt-GNU
for page in cpio.1 mt.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
cat cpio.info | gzip -9c > $PKG/usr/info/cpio.info.gz

# Build the package:
cd $PKG
tar czvf $TMP/cpio.tgz .

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/cpio-2.3
  rm -rf $PKG
fi
