#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-xlock
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
tar xzvf $CWD/_xlock.tar.gz

echo "+================+"
echo "| xlockmore-4.12 |"
echo "+================+"
cd $TMP
tar xzvf $CWD/xlockmore-4.12.tar.gz
cd xlockmore-4.12
mkdir -p $PKG/usr/X11R6/include/X11/bitmaps
cp $CWD/l-bob.xbm $PKG/usr/X11R6/include/X11/bitmaps
cp $CWD/l-linux.xbm $PKG/usr/X11R6/include/X11/bitmaps
mkdir $PKG/usr/doc/xlockmore-4.12
cp -a README $PKG/usr/doc/xlockmore-4.12/README
cp -a docs/* $PKG/usr/doc/xlockmore-4.12
cp -a $CWD/l-bob.README $PKG/usr/doc/xlockmore-4.12
chown root.root $PKG/usr/doc/xlockmore-4.12/*
# Normal compile:
configure --prefix=/usr/X11R6 --without-opengl --without-mesagl \
  --without-dtsaver --without-rplay --without-nas --disable-bomb
# Use MesaGL/OpenGL:
#configure --prefix=/usr/X11R6 \
#  --without-dtsaver --without-rplay --without-nas --disable-bomb
make CFLAGS=-O2 LDFLAGS=-s
cd xlock
strip xlock
cat XLock.ad > $PKG/var/X11R6/lib/app-defaults/XLock
cat xlock > $PKG/usr/X11R6/bin/xlock
cat xlock.man | gzip -9c > $PKG/usr/X11R6/man/man1/xlock.1.gz

# Build the package:
cd $PKG
tar czvf $TMP/xlock.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/xlockmore-4.12
  rm -rf $PKG
fi
