#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-byacc
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_byacc.tar.gz

echo "+=======+"
echo "| byacc |"
echo "+=======+"
cd $TMP
tar xzvf $CWD/byacc.tar.gz
cd byacc
make
strip yacc
cat yacc > $PKG/usr/bin/yacc
cat yacc.1 | gzip -9c > $PKG/usr/man/man1/yacc.1.gz

# Build the package:
cd $PKG
tar czvf $TMP/byacc.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/byacc
  rm -rf $PKG
fi
