#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES A (BASE LINUX SYSTEM)" \
       --checklist "Please select the packages you wish to install \
from series A. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Certain important packages have \
already been selected for you, and you are cautioned against unselecting \
these packages. However, it's your system. :^)  For instance, be sure to \
install LILO or you won't be able to make system bootdisks. \
Press ENTER when you are \
done." 21 72 8 \
"aaa_base" "Basic filesystem, shell, and utils - REQUIRED" "on" \
"bash" "GNU bash-1.14.7 shell - REQUIRED" "on" \
"devs" "Device files found in /dev - REQUIRED" "on" \
"etc"  "System config files & utilities - REQUIRED" "on" \
"shadow" "Shadow password suite - REQUIRED" "on" \
"ide"  "Linux 2.2.6 no SCSI (YOU NEED 1 KERNEL)" "on" \
"scsi" "Linux 2.2.6 with SCSI (YOU NEED 1 KERNEL)" "on" \
"modules" "Modular Linux device drivers" "on" \
"modutils" "Kernel module utilities -- REQUIRED" "on" \
"scsimods" "Loadable SCSI, RAID, and CD-ROM drivers" "on" \
"fsmods" "Loadable filesystem drivers" "on" \
"hdsetup" "Slackware setup scripts - REQUIRED" "on" \
"lilo" "Boot loader for Linux, DOS, OS/2, etc." "on" \
"bsdlpr" "BSD lpr - printer spooling system" "on" \
"loadlin" "Boots Linux (UMSDOS too!) from MS-DOS" "on" \
"pnp" "Plug'n'Play configuration tool" "on" \
"pciutils" "Linux PCI utilities" "on" \
"umsprogs" "Utilities needed to use the UMSDOS filesystem" "on" \
"sysvinit" "System V-like INIT programs - REQUIRED" "on" \
"bin"      "Various system utilities - REQUIRED" "on" \
"elvis" "elvis text editor (vi clone) - REQUIRED" "on" \
"fileutls" "GNU file utilities - REQUIRED" "on" \
"ldso" "Dynamic linker/loader - REQUIRED" "on" \
"ibcs2" "Runs SCO/SysVr4 binaries" "off" \
"less" "A text pager utility - REQUIRED" "on" \
"pcmcia" "PCMCIA card services support" "on" \
"getty" "Getty_ps 2.0.7j - OPTIONAL" "off" \
"gzip"  "GNU zip compression utility - REQUIRED" "on" \
"bzip2"  "bzip2 compression utility" "on" \
"procps" "Displays process info - REQUIRED" "on" \
"aoutlibs" "a.out shared libs - RECOMMENDED" "on" \
"elflibs" "The ELF shared C libraries - REQUIRED" "on" \
"glibc1" "Runtime glibc support libraries" "on" \
"glibc2" "Internationalization support for glibc" "on" \
"util" "Util-linux utilities - REQUIRED" "on" \
"minicom" "Serial transfer and modem comm package" "on" \
"cpio" "The GNU cpio backup/archiving utility" "on" \
"e2fsbn" "Utilities for the ext2 file system" "on" \
"find" "GNU findutils 4.1" "on" \
"grep" "GNU grep 2.3 - REQUIRED" "on" \
"kbd" "Change keyboard mappings" "on" \
"gpm" "Cut and paste text with your mouse" "on" \
"sh_utils" "GNU sh-utils 1.16 - REQUIRED" "on" \
"sysklogd" "Logs system and kernel messages" "on" \
"tar" "GNU tar 1.12 - REQUIRED" "on" \
"tcsh" "Extended C shell version 6.07" "on" \
"txtutils" "GNU textutils-1.22 - REQUIRED" "on" \
"zoneinfo" "Configures your time zone" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in aaa_base aoutlibs bash cpio devs etc grep bin gzip e2fsbn elflibs \
  find getty gpm hdsetup ibcs2 ide kbd less ldso lilo loadlin bsdlpr pnp \
  umsprogs minicom modules procps sysklogd pcmcia pciutils \
  scsi sh_utils sysvinit scsimods fsmods fileutls glibc1 glibc2 \
  shadow tar tcsh txtutils util zoneinfo bzip2 modutils elvis ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in aaa_base devs etc shadow ide scsi lilo sysvinit bin ldso \
bash getty gzip procps aoutlibs elflibs util fsmods elvis \
minicom cpio e2fsbn find grep kbd fileutls glibc1 glibc2 pciutils \
bsdlpr less gpm sh_utils hdsetup sysklogd tar tcsh txtutils zoneinfo \
modules scsimods ibcs2 umsprogs loadlin pcmcia pnp bzip2 modutils ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
