#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-umsprogs
SRC=/devel/manpagesrc
INFO=/devel/info-pages/usr/info
TEX=/devel/texinfo-docs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_umsprogs.tar.gz

# Function to handle manpage source:
man2gz () { # $1 is source page name, $2 is target name for preformatted
            # output (full path && name) and $3 is the same, but for the
            # source.
  mkdir -p `dirname $2`
  groff -Tascii -mandoc $1 | gzip -9c > $2
  if [ ! "$3" = "" ]; then
    mkdir -p `dirname $3`
    cat $1 > $3 
  fi 
}

echo "+==================+"
echo "| umsdos_progs-0.9 |"
echo "+==================+"
#echo "************* Recommend not using shared libg++"
cd $TMP
tar xzvf $CWD/umsdos_progs-0.9.src.tar.gz
cd umsdos_progs-0.9
make
cd util
strip umssync
cat umssync > $PKG/sbin/umssync
cat umssync.8 | gzip -9c > $PKG/usr/man/man8/umssync.8.gz

# Build the package:
cd $PKG
tar czvf $TMP/umsprogs.tgz .

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/umsdos_progs-0.9
  rm -rf $PKG
fi
