#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES AP (APPLICATIONS)" \
       --checklist "Please select the packages you wish to install \
from series AP. Use the \
UP/DOWN keys to scroll through the list, and the SPACE key to select \
the packages you wish to install. Recommended packages have \
already been selected for you, but you may unselect them if you wish. \
Press ENTER when you are \
done." 22 70 11 \
"apsfilt" "APSfilter - very useful printer utility" "on" \
"ispell" "The International version of ispell" "off" \
"jove" "Jonathan's Own Version of Emacs text editor" "off" \
"manpages" "man pages (online docs -- requires groff)" "on" \
"groff" "GNU troff document formatting system" "on" \
"diff" "GNU diffutils" "on" \
"sudo" "Allow special users limited root access" "off" \
"ghostscr" "GNU Ghostscript version 5.10" "on" \
"gsfonts" "Ghostscript fonts" "on" \
"enscript" "A text to PostScript utility" "off" \
"cdutils" "CD-R mastering/burning tools" "off" \
"jed" "JED programmer's editor" "on" \
"joe" "joe text editor, version 2.8" "on" \
"jpeg6" "JPEG image compression utilities" "on" \
"bc" "GNU bc - arbitrary precision math language" "off" \
"workbone" "a text-based audio CD player" "on" \
"mc" "The Midnight Commander file manager" "on" \
"md" "MD (RAID) utilities" "on" \
"mt_st" "mt ported from BSD - controls tape drive" "on" \
"quota" "User disk quota utilities" "on" \
"sc" "The 'sc' spreadsheet" "off" \
"seejpeg" "An SVGAlib image viewer" "on" \
"sox" "Sound utilities" "on" \
"texinfo" "GNU texinfo documentation system" "on" \
"vim" "Improved vi clone" "on" \
"ash" "A small /bin/sh type shell - 62K" "off" \
"zsh" "Zsh - a custom *nix shell" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in ash bc diff ghostscr gsfonts joe mt_st quota sudo groff ispell \
  jpeg6 workbone jove jed manpages mc sc texinfo vim zsh sox \
  seejpeg md cdutils enscript apsfilt ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in ispell jove manpages bc \
groff sc workbone ghostscr gsfonts joe md seejpeg \
mc jpeg6 ash jed mt_st texinfo vim sudo diff zsh sox cdutils \
quota enscript apsfilt ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
